# Form implementation generated from reading ui file 'ui/login_form.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_form(object):
    def setupUi(self, login_form):
        login_form.setObjectName("login_form")
        login_form.resize(544, 310)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=login_form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 511, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textLogin = QtWidgets.QTextBrowser(parent=self.gridLayoutWidget)
        self.textLogin.setObjectName("textLogin")
        self.gridLayout.addWidget(self.textLogin, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.gridLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.textPassword = QtWidgets.QTextBrowser(parent=self.gridLayoutWidget)
        self.textPassword.setObjectName("textPassword")
        self.gridLayout.addWidget(self.textPassword, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.retranslateUi(login_form)
        self.buttonBox.accepted.connect(login_form.accept) # type: ignore
        self.buttonBox.rejected.connect(login_form.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(login_form)

    def retranslateUi(self, login_form):
        _translate = QtCore.QCoreApplication.translate
        login_form.setWindowTitle(_translate("login_form", "Dialog"))
        self.label.setText(_translate("login_form", "Password"))
        self.label_2.setText(_translate("login_form", "Login"))
