# Form implementation generated from reading ui file 'ui/login_form.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_form(object):
    def setupUi(self, login_form):
        login_form.setObjectName("login_form")
        login_form.resize(544, 310)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=login_form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 511, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.textLogin = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.textLogin.setObjectName("textLogin")
        self.gridLayout.addWidget(self.textLogin, 1, 0, 1, 1)
        self.textPassword = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.textPassword.setObjectName("textPassword")
        self.gridLayout.addWidget(self.textPassword, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ButtonOk = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.ButtonOk.setObjectName("ButtonOk")
        self.horizontalLayout.addWidget(self.ButtonOk)
        self.ButtonClose = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.ButtonClose.setObjectName("ButtonClose")
        self.horizontalLayout.addWidget(self.ButtonClose)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)

        self.retranslateUi(login_form)
        QtCore.QMetaObject.connectSlotsByName(login_form)

    def retranslateUi(self, login_form):
        _translate = QtCore.QCoreApplication.translate
        login_form.setWindowTitle(_translate("login_form", "Dialog"))
        self.label.setText(_translate("login_form", "Password"))
        self.label_2.setText(_translate("login_form", "Login"))
        self.ButtonOk.setText(_translate("login_form", "Вход"))
        self.ButtonClose.setText(_translate("login_form", "Выход"))
