# Form implementation generated from reading ui file 'ui/main_form.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(992, 619)
        MainWindow.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(255, 170, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(84, 84, 84);\\ncolor: rgb(255, 170, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 991, 611))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(0, 85, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.TextBoxGenerate = QtWidgets.QTextEdit(parent=self.tab)
        self.TextBoxGenerate.setGeometry(QtCore.QRect(10, 30, 941, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.TextBoxGenerate.setFont(font)
        self.TextBoxGenerate.setAutoFillBackground(False)
        self.TextBoxGenerate.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(255, 170, 0);\n"
"font: 75 12pt \"Consolas\";")
        self.TextBoxGenerate.setObjectName("TextBoxGenerate")
        self.ButtonGenerate = QtWidgets.QPushButton(parent=self.tab)
        self.ButtonGenerate.setGeometry(QtCore.QRect(10, 100, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonGenerate.setFont(font)
        self.ButtonGenerate.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(255, 170, 0);")
        self.ButtonGenerate.setObjectName("ButtonGenerate")
        self.LoggerText = QtWidgets.QTextBrowser(parent=self.tab)
        self.LoggerText.setGeometry(QtCore.QRect(10, 340, 941, 211))
        self.LoggerText.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(255, 170, 0);\n"
"font: 75 12pt \"Consolas\";")
        self.LoggerText.setObjectName("LoggerText")
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setGeometry(QtCore.QRect(20, 302, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"color: rgb(255, 170, 0);")
        self.label.setObjectName("label")
        self.TextStrenght = QtWidgets.QTextBrowser(parent=self.tab)
        self.TextStrenght.setGeometry(QtCore.QRect(110, 100, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.TextStrenght.setFont(font)
        self.TextStrenght.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(255, 170, 0);\n"
"font: 75 12pt \"Consolas\";")
        self.TextStrenght.setObjectName("TextStrenght")
        self.TextTtH = QtWidgets.QTextBrowser(parent=self.tab)
        self.TextTtH.setGeometry(QtCore.QRect(360, 100, 591, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.TextTtH.setFont(font)
        self.TextTtH.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"font: 75 12pt \"Consolas\";\n"
"color: rgb(255, 170, 0);")
        self.TextTtH.setObjectName("TextTtH")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 931, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableUserPassword = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        self.tableUserPassword.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(255, 170, 0);")
        self.tableUserPassword.setObjectName("tableUserPassword")
        self.tableUserPassword.setColumnCount(0)
        self.tableUserPassword.setRowCount(0)
        self.verticalLayout.addWidget(self.tableUserPassword)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Generator"))
        self.ButtonGenerate.setText(_translate("MainWindow", "Generate"))
        self.label.setText(_translate("MainWindow", "Log"))
        self.TextStrenght.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:72; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:15pt; font-weight:600;\"><br /></p></body></html>"))
        self.TextTtH.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:72; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:15pt; font-weight:600;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Generator"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "History"))
