# Form implementation generated from reading ui file 'ui/main_form.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(486, 553)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QtWidgets.QToolBox(parent=self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 461, 511))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolBox.setFont(font)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 461, 455))
        self.page.setObjectName("page")
        self.ButtonGenerate = QtWidgets.QPushButton(parent=self.page)
        self.ButtonGenerate.setGeometry(QtCore.QRect(10, 100, 141, 51))
        self.ButtonGenerate.setObjectName("ButtonGenerate")
        self.TextBoxGenerate = QtWidgets.QTextEdit(parent=self.page)
        self.TextBoxGenerate.setGeometry(QtCore.QRect(0, 10, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TextBoxGenerate.setFont(font)
        self.TextBoxGenerate.setObjectName("TextBoxGenerate")
        self.listPassword = QtWidgets.QListView(parent=self.page)
        self.listPassword.setGeometry(QtCore.QRect(260, 10, 201, 441))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.listPassword.setFont(font)
        self.listPassword.setObjectName("listPassword")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 461, 455))
        self.page_2.setObjectName("page_2")
        self.LoggerText = QtWidgets.QTextBrowser(parent=self.page_2)
        self.LoggerText.setGeometry(QtCore.QRect(10, 0, 441, 481))
        self.LoggerText.setObjectName("LoggerText")
        self.toolBox.addItem(self.page_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Generator"))
        self.ButtonGenerate.setText(_translate("MainWindow", "Generate"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Generator"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Logger"))
